/*
 * mountlist.c - Format an AmigaDOS MountList from RDB partition data.
 *
 * See mountlist.h.  Every value comes straight out of the partition's
 * DosEnvVec as captured in struct PartInfo, so the file the user gets back is
 * an exact textual round-trip of what the RDB would mount.
 */

#include <exec/types.h>
#include <dos/dos.h>
#include <proto/dos.h>

#include "clib.h"
#include "mountlist.h"

/* Write a NUL-terminated string to fh; TRUE only if the whole string went. */
static BOOL ml_puts(BPTR fh, const char *s)
{
    LONG len = (LONG)strlen(s);
    if (len == 0) return TRUE;
    return (Write(fh, (APTR)s, len) == len);
}

/* Geometry can be stored per-partition; fall back to the RDB geometry when a
 * partition leaves heads/sectors at zero (matches cmd_info's size logic). */
static ULONG pi_heads(const struct RDBInfo *rdb, const struct PartInfo *pi)
{
    return (pi->heads > 0) ? pi->heads : rdb->heads;
}
static ULONG pi_sectors(const struct RDBInfo *rdb, const struct PartInfo *pi)
{
    return (pi->sectors > 0) ? pi->sectors : rdb->sectors;
}

/* Find a filesystem handler file name in the RDB matching this DosType.
 * Returns the path (e.g. "L:pfs3aio") or NULL when none / handler embedded. */
static const char *fs_handler_name(const struct RDBInfo *rdb, ULONG dos_type)
{
    UWORD i;
    for (i = 0; i < rdb->num_fs; i++) {
        const struct FSInfo *fi = &rdb->filesystems[i];
        if (fi->dos_type == dos_type && fi->fs_name[0] != '\0')
            return fi->fs_name;
    }
    return NULL;
}

BOOL MountList_Write(BPTR fh, const struct RDBInfo *rdb,
                     const char *devname, ULONG unit, UWORD *out_count)
{
    char  line[128];
    BOOL  ok = TRUE;
    UWORD i, written = 0;
    const char *dev = (devname && devname[0]) ? devname : "scsi.device";

    if (out_count) *out_count = 0;

    ok &= ml_puts(fh, "/* MountList generated by DiskPart - one entry per RDB partition. */\n");
    DP_SNPRINTF(line, "/* Source device: %s unit %lu */\n", dev, unit);
    ok &= ml_puts(fh, line);
    if (!devname || !devname[0])
        ok &= ml_puts(fh,
            "/* WARNING: source is an image file - edit Device/Unit below before use. */\n");
    ok &= ml_puts(fh, "\n");

    for (i = 0; i < rdb->num_parts; i++) {
        const struct PartInfo *pi = &rdb->parts[i];
        const char *fsname;

        /* Partition key, e.g. "DH0:" */
        DP_SNPRINTF(line, "%s:\n", pi->drive_name);
        ok &= ml_puts(fh, line);

        DP_SNPRINTF(line, "    Device          = %s\n", dev);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Unit            = %lu\n", unit);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Flags           = %lu\n", pi->dev_flags);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Surfaces        = %lu\n", pi_heads(rdb, pi));
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    SectorsPerBlock = %lu\n",
                    pi->sectors_per_block ? pi->sectors_per_block : 1UL);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    BlocksPerTrack  = %lu\n", pi_sectors(rdb, pi));
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Reserved        = %lu\n", pi->reserved_blks);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Interleave      = %lu\n", pi->interleave);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    LowCyl          = %lu\n", pi->low_cyl);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    HighCyl         = %lu\n", pi->high_cyl);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Buffers         = %lu\n", pi->num_buffer);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    BufMemType      = %lu\n", pi->buf_mem_type);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    MaxTransfer     = 0x%08lX\n", pi->max_transfer);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    Mask            = 0x%08lX\n", pi->mask);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    BootPri         = %ld\n", (long)pi->boot_pri);
        ok &= ml_puts(fh, line);
        DP_SNPRINTF(line, "    DosType         = 0x%08lX\n", pi->dos_type);
        ok &= ml_puts(fh, line);
        if (pi->block_size && pi->block_size != 512UL) {
            DP_SNPRINTF(line, "    BlockSize       = %lu\n", pi->block_size);
            ok &= ml_puts(fh, line);
        }
        if (pi->control) {
            DP_SNPRINTF(line, "    Control         = %lu\n", pi->control);
            ok &= ml_puts(fh, line);
        }

        fsname = fs_handler_name(rdb, pi->dos_type);
        if (fsname) {
            DP_SNPRINTF(line, "    FileSystem      = %s\n", fsname);
            ok &= ml_puts(fh, line);
            ok &= ml_puts(fh, "    GlobVec         = -1\n");
        }

        ok &= ml_puts(fh, "    Mount           = 1\n");
        ok &= ml_puts(fh, "#\n\n");

        written++;
    }

    if (out_count) *out_count = written;
    return ok;
}
